- serpens/api.py
- tests/test_api.py
* Update api handler to inject a request object that contains the full event data, an attribute called `authorizer` and another called `body`. The `authorizer` maps whatever came inside the requestContext->authorizer, and the body returns a dict if the content is "json serializable", otherwise the content as is.
```python
import api
@api.handler
def my_handler(request):
print(request.authorizer.some_id)
print(request.body)
...
```
* Add tests.
> feat: improve api handler

- serpens/schema.py
- tests/test_schema.py
* Add a new base class to help with schema validation. This base class uses Python's type annotation to validate inputted data.
```python
from dataclasses import dataclass
from schema import Schema
@dataclass
class PersonSchema(Schema):
name: str
age: int
>>> Person('John', 18)
... Person(name=John, age=18)
>>> Person('Foo', 'Bar')
... TypeError: ("'age' must be of type int",)
```
> feat: add base class for schema validation

- serpens/schema.py
- tests/test_schema.py
* Add methods to encode and decode data converting from json or json strings to an instance of the schema, and from an instance to a json (serializable) or json string.
```python
from dataclasses import dataclass
from schema import Schema
@dataclass
class PersonSchema(Schema):
name: str
age: int
>>> p = Person('John', 18)
>>> p
... Person(name=John, age=18)
>>> j = Person.dump(p)
>>> j
... {'name': 'John', 'age': 18}
>>> Person.load(j)
... Person(name=John, age=18)
```
> feat: add load, loads, dump and dumps methods for schemas

- serpens/api.py
This will allow to make use of safe access of an attribute, when a `None` value is returned in case of the attribute does not exists instead of raising an exception. It works exactly as the `get` method of dictionaries.
> feat: add method `get` to AttrDict class

- Makefile
- serpens/cache.py
- serpens/schema.py
There are message events with ISO8601 format for datetime, i.e. `2021-04-23T13:15:48.747Z` which is not soported by `.fromisoformat()`, só it is applied a mask in order to recognize this format
> feat: add schema compatibility for datetime ISO8601 format

- serpens/schema.py
- tests/test_schema.py
By default dataclasses raises exceptions for missing required fields as follow:
```python
@dataclass
class Foo:
bar: str
baz: int
f = Foo()
...
TypeError: __init__() missing 2 required positional arguments: 'bar' and 'baz'
```
This changes make the `load` and `loads` methods from `Schema` class override the default error message that will look like:
```python
@dataclass
class Foo(Schema):
bar: str
baz: int
f = Foo.load({})
...
TypeError: ("'bar' is a required field", "'baz' is a required field")
```
> feat: improve schemas error messages for missing required fields

- serpens/api.py
- tests/test_api.py
* Add two extra "pre-parsed" attributes to the API helper class `Request`:
* `headers` - HTTP request headers.
* `identity` - AWS ApiGateway identity information.
> feat: improve request class

- serpens/api.py
We always use initializers.setup every place we decorete with
api.handler so it is better to setup it by default.
Now in places like this:
```python
from serpens import initializers, api
from proposal import Proposal, ProposalInfo
initializers.setup()
@api.handler
def score_proposal_handler(request: api.Request):
req_info = ProposalInfo(**request.body)
proposal = Proposal.get_proposal_for_score(req_info)
return 200, proposal
```
we could use just:
```python
from serpens import api
from proposal import Proposal, ProposalInfo
@api.handler
def score_proposal_handler(request: api.Request):
req_info = ProposalInfo(**request.body)
proposal = Proposal.get_proposal_for_score(req_info)
return 200, proposal
```
> Auto initialize setup on api.handle

- serpens/envvars.py
- tests/test_envvars.py
- Add condition to treat undefined envvar.
- Raise exception if envvar is not defined.
- Update tests.
> Add treatment to undefined envvar

- serpens/api.py
- setup.py
- tests/test_api.py
- Fix default header for API Response class instances.
- Add missing unit tests.
> fix: default header for api response class

- requirements-dev.txt
- serpens/envvars.py
- serpens/secrets_manager.py
- tests/test_envvars.py
- tests/test_secrets_manager.py
- Rename secrets module to secrets_manager to avoid conflicts with Python's core library
> Rename secrets module

- serpens/validators.py
- setup.py
- tests/test_validators.py
* Update test case to have phone_numer with +55 and without
* Accept phone number with +55 and without on validate_pix
* Bump setup version to 2.0.0a8
> Feat/accept key with +55 and without

- .github/workflows/publish.yml
Fix reference to base workflow on PyPI's publishing workflow.
> fix: base workflow reference

- .github/workflows/publish.yml
- GitHub Actions does not allow access to reusable workflows in private repositories from a public one.
> refactor: do not use re-usable workflow due gha permissions

- pyproject.toml
- serpens/elastic.py
- serpens/elastic_sanitize.py
- tests/test_elastic.py
- tests/test_elastic_sanitize.py
Add method to sanitize request body using JSON. The elasticapm.processors.sanitize_http_request_body method just sanitize Form URL encoded requests.
> feat: elastic sanitize

- serpens/api.py
- serpens/elastic.py
- serpens/elastic_sanitize.py
- tests/test_api.py
- tests/test_elastic.py
- tests/test_elastic_sanitize.py
Added a method to standardize response body storage in Elastic APM. This method hides personal data fields.
The list of personal data fields can be modified using the ELASTIC_APM_SANITIZE_FIELD_NAMES environment variable.
> feat: add elastic capture response

- serpens/elastic.py
- serpens/elastic_sanitize.py
- tests/test_elastic.py
- tests/test_elastic_sanitize.py
- Elastic APM request body changed to string. This is required for list-type request bodies to be compatible with ELK.
- Added check to only set ELASTIC_APM_PROCESSORS if this environment variable is not set. This makes it possible to disable the ELK's default processors.
> feat: changed Elastic APM request body to string

- pyproject.toml
- serpens/api.py
Simplified logger exception call in the API module, because the logger_exception method in the sentry module was deprecated. The manual flush Sentry is not good way to prevent lose logs.
> fix: simplified logger exception call in the API module

- serpens/validators.py
- tests/test_validators.py
- Fix name validation to match one character that is not a non-word character, in order to let names like "D'Artagnan" pass the validation
> fix: name validation to match one character that is not a non-word character

- serpens/api.py
- Remove `capture_serverless` function call from api wrapper function.
- According to the [docs](https://www.elastic.co/guide/en/apm/agent/python/current/lambda-support.html) this is not necessary anymore.
> fix: apm spindown issue for wrapped api handlers

- serpens/sqs.py
- Remove `capture_serverless` function call from sqs wrapper function.
- According to the [docs](https://www.elastic.co/guide/en/apm/agent/python/current/lambda-support.html) this is not necessary anymore.
> fix: apm spindown issue for wrapped sqs handlers

- serpens/pubsub.py
In MessageClient we defined order_key with None default value, which cause an error in pub sub that expect "" if not provided ordering.
> fix: check if ordering key is None

- serpens/pubsub.py
* Update publisher client options to enable ordering messages
[Task 151538](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/151538): Criar função para públicar mensagens em lote
> fix: update publisher client options to enable ordering messages
