noverde/serpens

serpens/api.py, tests/test_api.py
* Update `Request` class in `api` module to provide new information coming from the request: the path parameters and the query parameters.
* Update api unit tests.
=> feat: improve api request object

serpens/schema.py
* Skip type validation for optional fields when it is `None` and default value is `None`
=> feat: skip type validation for optional fields in schemas

serpens/sns.py
* Add sns integration to publish messages
=> feat: add sns publish message

serpens/sns.py
* Add sns create message event
=> feat: add sns create message event

serpens/s3.py, tests/test_s3.py
* Add function to upload files to AWS S3.
=> feat: add helper function to upload files to s3

serpens/rekognition.py, tests/test_rekognition.py
- Add new helper function to perform _face detection_ on AWS S3 Objects using AWS Recognition service.
=> feat: face detection using aws rekognition

serpens/cache.py
Example of usage
```
from serpens import cache
@cache.cached("test", 3)
def test(a, b):
return 1
test(1, 2)
test(1, 2)
cache.clear_cache("test")
test(1, 2)
test(3,4)
test(3,4)
```
=> adding in memory cache feature

serpens/parameters.py, serpens/secrets.py, tests/test_parameters.py, tests/test_secrets.py
This pull request are opened to allow cache information in parameter store and secrets manager on AWS
=> feat: cache secrets and parameters

serpens/parameters.py, serpens/secrets.py
This pull request will be fix a import problem in serpens.
=> fix: Imports with `serpens`

serpens/s3.py, tests/test_s3.py
*  Add get_file fucntion to download file from bucket
*  Add exists function to check if a file exists in the given bucket
=> feat: add s3 functions

serpens/api.py
* Adding received data log debug to api handler
=> Feature: Adding received data log debug to api handler

tests/test_sns.py, tests/test_sqs.py
* Add tests for `SNS` and `SQS` modules.
=> test: improve test coverage

serpens/migrations.py, serpens/settings.py, setup.py
Now we can use a default migration to migrate database on standard way.
=> Database migration handler

README.md, serpens/settings.py, serpens/sqs.py, setup.py, tests/test_sqs.py
- Create sqs decorator.
- Create documentation in README for sqs decorator.
- Create tests.
- Refactor Record class from sqs module.
- Add documentations from another modules in README.
=> Add SQS decorator. Add documentations.

serpens/api.py, serpens/settings.py, setup.py
- Fix sending duplicate messages to sentry.
- Update tests.
=> Fix sending duplicate messages to sentry

serpens/settings.py, serpens/sqs.py, setup.py
- Add initializers to SQS utilities
- Bump version to v1.14.1
=> Add initializers to SQS utilities

serpens/validators.py
* Remove palindromes from CPF validation
* Add CPF with all same digits validation
[PLAT-1333](https://noverde.atlassian.net/browse/PLAT-1333)
=> fix: Adjust CPF validator for palindromes

setup.py
* Add right version number in steup.py
=> fix: Update version value in setup

serpens/api.py, setup.py, tests/test_api.py
- Add response class to api handler wrapper
=> feat: add response class in api handler wrapper function

serpens/s3.py, tests/test_s3.py
=> Feat: Update functions name

tests/test_testgres.py
=> Add new tests

serpens/sentry.py, tests/test_sentry.py
- Add base class for exceptions that shouldn't be sent to Sentry
- Add `before_send` method
- Add test cases
=> Sentry improvements

serpens/api.py, serpens/sentry.py, tests/test_sentry.py
* Add function to sentry module to handle with exceptions.
Article about the implementation: https://docs.sentry.io/platforms/python/configuration/draining/
JIRA card: [Verificar não envio de erros ao sentry](https://noverde.atlassian.net/browse/SRE-216?atlOrigin=eyJpIjoiMDY1ZTM1MjkwN2FlNGMzNjlhODE4MjU4ZTllODk3Y2YiLCJwIjoiaiJ9)
=> Add function to close sentry client manually

setup.py
=> Update setup version to 2.0.0a7

serpens/sqs.py, setup.py, tests/test_sqs.py
* Update sqs publish message function to check if body is a dict and dumps with encoder if true
=> feat: improve publish message sqs to dumps dict

serpens/testgres.py, setup.py, tests/test_testgres.py
- Enable postgresql user's search path configuration for testgres.
=> feat: add user's search path configuration for testgres

serpens/migrations.py
* fix: set migrations path correctly in migrations module
=> fix: set path migrations correctly

serpens/migrations.py
* fix: add initializers setup in migrations module
=> fix: add initializers in migrations module

serpens/lambda_function.py, setup.py, tests/test_lambda_function.py
*  Add function to invoke lambda
*  Add test cases
=> feat: add lambda function invoke

serpens/s3.py, tests/test_s3.py
*  Add function generate_presigned_url for s3 files
=> feat: add function generate_presigned_url for s3 files

serpens/validators.py, tests/test_validators.py
- Add name validate method
- [AZDO 135063 - [platform-accounts] Arrumar expressões regulares de nomes que estão aceitando digitos numéricos no Python](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/135063)
=> Add name validate method

serpens/sqs.py, tests/test_sqs.py
Add Attributes to send_message
https://dotzmkt.visualstudio.com/Arquitetura/_boards/board/t/Arquitetura%20Team/Stories/?workitem=135158
=> fix: add attributes to send message sqs

setup.py, tests/test_schema.py
Improve code to not assigned NULL to attributes not Optional. "field" is resource of dataclass to assigned default value (attribute not required).
=> fix: code smell in test_schema.py

.github/workflows/publish.yml
Add GitHub Actions workflow to publish to PyPI.
=> feat: add workflow to publish to pypi

pyproject.toml
- Fix package long description configuration on `pyproject.toml` file.
=> fix: package long description configuration on pyproject file

requirements-dev.txt, tests/fixtures/fixtures.py, tests/test_document.py
- Update development tools.
- Fix test issues due to the upgrade of black and moto.
=> deps: update development tools

.github/workflows/tests.yml, Makefile, requirements-dev.txt, tests/test_schema.py
- Update tests workflow.
- Add two new steps to build and validate the generated package.
=> feat: improve tests workflow

serpens/sqs.py, tests/test_sqs.py
https://dotzmkt.visualstudio.com/Arquitetura/_boards/board/t/Arquitetura%20Team/Stories/?workitem=145189
=> feat: improve send message batch

serpens/compute_engine.py, tests/test_compute_engine.py
Add function to acquire compute token from gcp service account
=> feat: add compute engine module with acquire token from gcp

serpens/sqs.py
* Check if attributes is none
[Task 151457](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/151457): Refatorar modulo sqs
=> feat: check if attributes is none

.vscode/settings.json, pyproject.toml, requirements-dev.txt, serpens/pubsub.py, tests/test_pubsub.py
* add publish message function
[Task 151200](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/151200): Criar função para publicar mensagem no PubSub
=> feat: add publish message function

serpens/pubsub.py
* Remove duplicate code
[Task 151200](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/151200): Criar função para publicar mensagem no PubSub
=> refactor: remove duplicate code

serpens/messages.py, serpens/sqs.py, tests/test_messages.py
=> feat: add publish batch messages

serpens/storages.py, tests/test_storage.py
* Add storage facade
[Task 152234](https://dotzmkt.visualstudio.com/Arquitetura/_workitems/edit/152234): criar modulo google_storage para buscar arquivos no storage
=> feat: storage facede

requirements-dev.txt, serpens/cloud_storage.py, tests/test_cloud_storage.py
Add module to stream objects from google cloud storage
=> feat: add module to get object from cloud storage stream mode

requirements-dev.txt, serpens/testgres.py
* Add postgres startup delay config
=> Postgres startup delay config

pyproject.toml
=> chore: bump version to 2.7.0
